# reload config file
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# COLOR PALETTE
C_BACKGROUND="default"
C_FOREGROUND="default"
C_PRIMARY="green"
C_DANGER="red"
C_SURFACE="white"
C_ON_SURFACE="black"
C_POWERLINE="#080808"

# CONFIGS
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set-option -g status-interval 1
set-option -g allow-rename off
set-option -g automatic-rename-format "#{b:pane_current_path}"

# VIM
setw -g mode-keys vi
set -sg escape-time 0

# KEYBINDS
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

bind q kill-pane
bind Q kill-window

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# change window using alt-(1-0)
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind "'"
unbind %
unbind &

# Panes navigation using vim-like
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# VISUAL
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# STATUS BAR
set -g status-style bg=$C_BACKGROUND

# Left module
set -g status-left " #[fg=$C_FOREGROUND, bold]Tmux (#S) #{?client_prefix,#[fg=$C_DANGER]COMMAND ,#[fg=$C_PRIMARY]NORMAL }"
set -g status-left-length 30

# Middle module - inactive windows
set -g window-status-format "#[bg=$C_SURFACE,fg=$C_POWERLINE]#[bg=$C_SURFACE,fg=$C_ON_SURFACE] #I:#W #[bg=$C_BACKGROUND,fg=$C_SURFACE]"
# Middle module - active window
set -g window-status-current-format "#[bg=$C_PRIMARY,fg=$C_POWERLINE]#[bg=$C_PRIMARY,fg=$C_ON_SURFACE] #I:#W #[bg=$C_BACKGROUND,fg=$C_PRIMARY]"
set -g window-status-separator ""

# Right module
set -g status-right ""

# Mode style (visual/copy mode)
setw -g mode-style "bg=$C_PRIMARY fg=$C_FOREGROUND bold"

# PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'pwnalone/tmux-name-generator'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
