# █▄ ▄█  █  █▀▀  █▀▀
# █░▀░█  █  ▄▄█  █▄▄


misc {
	middle_click_paste = false
	disable_hyprland_logo = true
	disable_splash_rendering = true
}

debug {
	disable_logs = true
	enable_stdout_logs = false
}


# █░░  ▄▀█  █░█  █▀█  █░█  ▀█▀  █▀▀
# █▄▄  █▀█   █   █▄█  █▄█  ░█░  ▄▄█


master {
	new_status = master
}

dwindle {
	preserve_split = true
}
